### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by chrzyki** [tupuni/polynesianoutliersvoyaging#2]
Instead of doing a PR that mixes inline comments with other fixes I'll just list my comments/observations here.

- leave .Rhistory (https://github.com/tupuni/polynesianoutliersvoyaging/blob/main/.Rhistory) out of the repository, add to `.gitignore`
- leave .DS_Store (https://github.com/tupuni/polynesianoutliersvoyaging/blob/main/.DS_Store and in other places) out of the repository, add to `.gitignore`
- fix placeholder comments in https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/.binder/Dockerfile#L1-L6
- the project makes use of more libraries implicitly than what is explicitly loaded: https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/DESCRIPTION#L9-L15
  - I needed to add at least: `dplyr, tidyverse, here, RSQLite`
- only `paper.qmd` exists at the location that is specified https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/README.Rmd#L60-L65
- `devtools` is never explicitly loaded/installed as far as I can tell so this fails without `devtools` as a requirement https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/README.Rmd#L63
- the binder link is not working https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/README.Rmd#L17-L20
- this happily accepts most paths/locations and then later fails during the SQL queries https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/analysis/helper-functions-globals.R#L4-L6
  - check validity of path/SQLite?
- I think `rename_georoc()` is never defined in this repository? Subsequently, this fails https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/analysis/sql-queries.R#L805-L810

**Comment by tupuni** [comment]
Thanks. As you probably noticed, I used the research compendium template of Ben Marwicks (rrtools). Here are my suggestions:

- [ ] leave .Rhistory (https://github.com/tupuni/polynesianoutliersvoyaging/blob/main/.Rhistory) out of the repository, add to .gitignore. **Great, could you fix that?** 
- [ ] leave .DS_Store (https://github.com/tupuni/polynesianoutliersvoyaging/blob/main/.DS_Store and in other places) out of the repository, add to .gitignore **Great, could you fix that?** 
- [ ] fix placeholder comments in [polynesianoutliersvoyaging/.binder/Dockerfile](https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/.binder/Dockerfile#L1-L6). **Ok, could you fix that?** 
- [x] the project makes use of more libraries implicitly than what is explicitly loaded. **Ok, done (I think it's ok)** 
- [x] only paper.qmd exists at the location that is specified in [polynesianoutliersvoyaging/README.Rmd](https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/README.Rmd#L60-L65) **Ok, I removed this part because we're not making the paper reproducible, only figures separately, I don't have time to write up the paper in html etc.** 
- [ ] devtools is never explicitly loaded/installed as far as I can tell so this fails without devtools as a requirement **Ok, it is cited [there](https://github.com/tupuni/polynesianoutliersvoyaging/blob/a65fd4abf8094eb1ea709123cae5d75b3fb88e7f/DESCRIPTION#L14). Shall it be mentionned somewhere else?** 
- [ ]  run `devtools::install()` to ensure you have the packages this analysis depends on (also listed in the 
the binder link is not working  **I might just remove [polynesianoutliersvoyaging/README.Rmd](https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/README.Rmd)** 
- [ ]  this happily accepts most paths/locations and then later fails during the SQL queries. ** I don't understand why sql queries fails after this is set in [polynesianoutliersvoyaging/analysis/helper-functions-globals.R](https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/analysis/helper-functions-globals.R#L4-L6)**
- [x] I think rename_georoc() is never defined in this repository? Subsequently, this fails. **Ok, fixed, I used to use a rename_georoc() function but not anymore. This was the only place it was left as a mistake. It's fixed, I changed the query https://github.com/tupuni/polynesianoutliersvoyaging/blob/b4cce74ca7a248bef2969e9173a164746578d6a5/analysis/sql-queries.R#L801-L813**

**Comment by chrzyki** [comment]
>     * [ ]   this happily accepts most paths/locations and then later fails during the SQL queries. ** I don't understand why sql queries fails after this is set in [polynesianoutliersvoyaging/analysis/helper-functions-globals.R](https://github.com/tupuni/polynesianoutliersvoyaging/blob/3586c07ed74e35c426c41b4424f66e997b98cd51/analysis/helper-functions-globals.R#L4-L6)**

The problem here is that the variables specifying the path to the two databases are never checked for 'anything' (validity of the path, proper SQL, etc.). For example, if a user specifies a path that doesn't exist or that is wrong (e.g. not the db but some other file) they later get SQL query errors because of the 'wrong' paths. This might be tricky to debug for some, because the connection between wrong database paths -> failing queries isn't immediately obvious.

**Comment by tupuni** [comment]
Hi @chrzyki and @xrotwang, what do you suggest regarding the specification of paths to SQL files?
I am now ready to submit the article to science advances, would it be possible to let me know exactly how to fix the remaining issues on the repos in the next days (or have a quick morning zoom about it to lead me through if), in order to publish it in Zenodo and finalize the referencing to this compendium to send the paper for submission?

**Comment by xrotwang** [comment]
I'd say they should be passed in on the commandline - but I don't know how that works within R-Studio.

**Comment by chrzyki** [comment]
> Hi @chrzyki and @xrotwang, what do you suggest regarding the specification of paths to SQL files? I am now ready to submit the article to science advances, would it be possible to let me know exactly how to fix the remaining issues on the repos in the next days (or have a quick morning zoom about it to lead me through if), in order to publish it in Zenodo and finalize the referencing to this compendium to send the paper for submission?

Hey Aymeric! I can either add some additional comments here or we do a quick Zoom on Thursday or Friday morning.

**Comment by tupuni** [comment]
Hi, yes I think a zoom would be better. I am available tonight and tursday+friday night, which means this morning (wednesday) or friday or saturday morning for you (I’m 11hours behind you). It can be anytime between 8 pm and midnight for me - 7 to 11 am for you.

**Comment by chrzyki** [comment]
Would tomorrow morning (our Friday 2022-11-18, around 8-9 CET) work?

/edit: Sorry, fixed the date.

**Comment by tupuni** [comment]
Yes that’s perfect. I’ll send an email with a zoom link. Thanks, see you then

**Comment by tupuni** [comment]
In README.Rmd change  Binder link https://mybinder.org/v2/gh/tupuni/polynesianoutliersvoyaging/master?urlpath=rstudio to https://mybinder.org/v2/gh/tupuni/polynesianoutliersvoyaging/main?urlpath=rstudio (master to main)

**Comment by tupuni** [comment]
Add instructions about the sqlite files: 
- make sure the file paths are right
- make it explicit that the reproduction of the paper is tied to specific version of the databases
- make it explicit that new results may come out when new data is released in the databases

**Comment by chrzyki** [comment]
All done.
